name: Generate and Publish Manifest

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v4

      - run: mise run ci

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          make_latest: true
